// Mocks generated by Mockito 5.4.6 from annotations
// in dart_lodge/test/features/game/presentation/providers/active_practice_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dart_lodge/core/utils/constants.dart' as _i5;
import 'package:dart_lodge/features/game/domain/entities/competitor.dart'
    as _i6;
import 'package:dart_lodge/features/game/domain/entities/dart_throw.dart'
    as _i11;
import 'package:dart_lodge/features/game/domain/entities/game.dart' as _i4;
import 'package:dart_lodge/features/game/domain/entities/game_event.dart'
    as _i9;
import 'package:dart_lodge/features/game/domain/models/game_state_snapshot.dart'
    as _i7;
import 'package:dart_lodge/features/game/domain/repositories/dart_throw_repository.dart'
    as _i10;
import 'package:dart_lodge/features/game/domain/repositories/game_event_repository.dart'
    as _i8;
import 'package:dart_lodge/features/game/domain/repositories/game_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GameRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRepository extends _i1.Mock implements _i2.GameRepository {
  MockGameRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Game?> getActiveGame() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveGame, []),
            returnValue: _i3.Future<_i4.Game?>.value(),
          )
          as _i3.Future<_i4.Game?>);

  @override
  _i3.Future<_i4.Game?> getGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getGame, [gameId]),
            returnValue: _i3.Future<_i4.Game?>.value(),
          )
          as _i3.Future<_i4.Game?>);

  @override
  _i3.Future<List<_i4.Game>> getCompletedGames({
    int? limit = 20,
    int? offset = 0,
    _i5.GameType? filterByType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedGames, [], {
              #limit: limit,
              #offset: offset,
              #filterByType: filterByType,
            }),
            returnValue: _i3.Future<List<_i4.Game>>.value(<_i4.Game>[]),
          )
          as _i3.Future<List<_i4.Game>>);

  @override
  _i3.Future<List<_i6.Competitor>> getCompetitors(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getCompetitors, [gameId]),
            returnValue: _i3.Future<List<_i6.Competitor>>.value(
              <_i6.Competitor>[],
            ),
          )
          as _i3.Future<List<_i6.Competitor>>);

  @override
  _i3.Future<void> createGame(
    _i4.Game? game,
    List<_i6.Competitor>? competitors,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createGame, [game, competitors]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveGameState(
    String? gameId,
    _i7.GameStateSnapshot? state,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveGameState, [gameId, state]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> completeGame({
    required String? gameId,
    required String? winnerCompetitorId,
    required DateTime? endTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeGame, [], {
              #gameId: gameId,
              #winnerCompetitorId: winnerCompetitorId,
              #endTime: endTime,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i4.Game?> watchActiveGame() =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveGame, []),
            returnValue: _i3.Stream<_i4.Game?>.empty(),
          )
          as _i3.Stream<_i4.Game?>);

  @override
  _i3.Stream<List<_i4.Game>> watchCompletedGames({
    _i5.GameType? filterByType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchCompletedGames, [], {
              #filterByType: filterByType,
            }),
            returnValue: _i3.Stream<List<_i4.Game>>.empty(),
          )
          as _i3.Stream<List<_i4.Game>>);
}

/// A class which mocks [GameEventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameEventRepository extends _i1.Mock
    implements _i8.GameEventRepository {
  MockGameEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i9.GameEvent>> getEventsForGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventsForGame, [gameId]),
            returnValue: _i3.Future<List<_i9.GameEvent>>.value(
              <_i9.GameEvent>[],
            ),
          )
          as _i3.Future<List<_i9.GameEvent>>);

  @override
  _i3.Future<List<_i9.GameEvent>> getEventsSince(
    String? gameId,
    int? afterSequence,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEventsSince, [gameId, afterSequence]),
            returnValue: _i3.Future<List<_i9.GameEvent>>.value(
              <_i9.GameEvent>[],
            ),
          )
          as _i3.Future<List<_i9.GameEvent>>);

  @override
  _i3.Future<List<_i9.GameEvent>> getUnsyncedEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedEvents, []),
            returnValue: _i3.Future<List<_i9.GameEvent>>.value(
              <_i9.GameEvent>[],
            ),
          )
          as _i3.Future<List<_i9.GameEvent>>);

  @override
  _i3.Future<int> getLatestSequence(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestSequence, [gameId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> appendEvent(_i9.GameEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#appendEvent, [event]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> appendEvents(List<_i9.GameEvent>? events) =>
      (super.noSuchMethod(
            Invocation.method(#appendEvents, [events]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markSynced(List<String>? eventIds) =>
      (super.noSuchMethod(
            Invocation.method(#markSynced, [eventIds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateGlobalSequences(Map<String, int>? eventIdToSequence) =>
      (super.noSuchMethod(
            Invocation.method(#updateGlobalSequences, [eventIdToSequence]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i9.GameEvent>> watchEventsForGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#watchEventsForGame, [gameId]),
            returnValue: _i3.Stream<List<_i9.GameEvent>>.empty(),
          )
          as _i3.Stream<List<_i9.GameEvent>>);
}

/// A class which mocks [DartThrowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDartThrowRepository extends _i1.Mock
    implements _i10.DartThrowRepository {
  MockDartThrowRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i11.DartThrow>> getDartsForGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getDartsForGame, [gameId]),
            returnValue: _i3.Future<List<_i11.DartThrow>>.value(
              <_i11.DartThrow>[],
            ),
          )
          as _i3.Future<List<_i11.DartThrow>>);

  @override
  _i3.Future<List<_i11.DartThrow>> getDartsForCompetitor(
    String? gameId,
    String? competitorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDartsForCompetitor, [gameId, competitorId]),
            returnValue: _i3.Future<List<_i11.DartThrow>>.value(
              <_i11.DartThrow>[],
            ),
          )
          as _i3.Future<List<_i11.DartThrow>>);

  @override
  _i3.Future<List<_i11.DartThrow>> getDartsForPlayer(
    String? playerId, {
    int? limit = 100,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDartsForPlayer,
              [playerId],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i3.Future<List<_i11.DartThrow>>.value(
              <_i11.DartThrow>[],
            ),
          )
          as _i3.Future<List<_i11.DartThrow>>);

  @override
  _i3.Future<void> insertDart(_i11.DartThrow? dart) =>
      (super.noSuchMethod(
            Invocation.method(#insertDart, [dart]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> insertDarts(List<_i11.DartThrow>? darts) =>
      (super.noSuchMethod(
            Invocation.method(#insertDarts, [darts]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDart(String? dartId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDart, [dartId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
