// Mocks generated by Mockito 5.4.6 from annotations
// in dart_lodge/test/features/game/presentation/providers/game_setup_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dart_lodge/core/utils/constants.dart' as _i9;
import 'package:dart_lodge/features/game/domain/entities/competitor.dart'
    as _i7;
import 'package:dart_lodge/features/game/domain/entities/game.dart' as _i2;
import 'package:dart_lodge/features/game/domain/entities/game_event.dart'
    as _i10;
import 'package:dart_lodge/features/game/domain/repositories/game_repository.dart'
    as _i8;
import 'package:dart_lodge/features/game/domain/usecases/create_game_use_case.dart'
    as _i6;
import 'package:dart_lodge/features/players/domain/entities/player.dart' as _i5;
import 'package:dart_lodge/features/players/domain/repositories/player_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGame_0 extends _i1.SmartFake implements _i2.Game {
  _FakeGame_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlayerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerRepository extends _i1.Mock implements _i3.PlayerRepository {
  MockPlayerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Player>> getAllPlayers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPlayers, []),
            returnValue: _i4.Future<List<_i5.Player>>.value(<_i5.Player>[]),
          )
          as _i4.Future<List<_i5.Player>>);

  @override
  _i4.Future<_i5.Player?> getPlayer(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlayer, [playerId]),
            returnValue: _i4.Future<_i5.Player?>.value(),
          )
          as _i4.Future<_i5.Player?>);

  @override
  _i4.Future<void> createPlayer(_i5.Player? player) =>
      (super.noSuchMethod(
            Invocation.method(#createPlayer, [player]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePlayerName(String? playerId, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlayerName, [playerId, name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> touchPlayer(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#touchPlayer, [playerId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePlayer(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlayer, [playerId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i5.Player>> watchAllPlayers() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllPlayers, []),
            returnValue: _i4.Stream<List<_i5.Player>>.empty(),
          )
          as _i4.Stream<List<_i5.Player>>);
}

/// A class which mocks [CreateGameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateGameUseCase extends _i1.Mock implements _i6.CreateGameUseCase {
  MockCreateGameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Game> execute(
    _i2.Game? game,
    List<_i7.Competitor>? competitors,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [game, competitors]),
            returnValue: _i4.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#execute, [game, competitors]),
              ),
            ),
          )
          as _i4.Future<_i2.Game>);
}

/// A class which mocks [GameRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRepository extends _i1.Mock implements _i8.GameRepository {
  MockGameRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Game?> getActiveGame() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveGame, []),
            returnValue: _i4.Future<_i2.Game?>.value(),
          )
          as _i4.Future<_i2.Game?>);

  @override
  _i4.Future<_i2.Game?> getGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getGame, [gameId]),
            returnValue: _i4.Future<_i2.Game?>.value(),
          )
          as _i4.Future<_i2.Game?>);

  @override
  _i4.Future<List<_i2.Game>> getCompletedGames({
    int? limit = 20,
    int? offset = 0,
    _i9.GameType? filterByType,
    DateTime? dateFrom,
    DateTime? dateTo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedGames, [], {
              #limit: limit,
              #offset: offset,
              #filterByType: filterByType,
              #dateFrom: dateFrom,
              #dateTo: dateTo,
            }),
            returnValue: _i4.Future<List<_i2.Game>>.value(<_i2.Game>[]),
          )
          as _i4.Future<List<_i2.Game>>);

  @override
  _i4.Future<List<_i7.Competitor>> getCompetitors(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getCompetitors, [gameId]),
            returnValue: _i4.Future<List<_i7.Competitor>>.value(
              <_i7.Competitor>[],
            ),
          )
          as _i4.Future<List<_i7.Competitor>>);

  @override
  _i4.Future<void> createGame(
    _i2.Game? game,
    List<_i7.Competitor>? competitors,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createGame, [game, competitors]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> completeGame({
    required String? gameId,
    required String? winnerCompetitorId,
    required DateTime? endTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeGame, [], {
              #gameId: gameId,
              #winnerCompetitorId: winnerCompetitorId,
              #endTime: endTime,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> appendEventsAndCompleteGame({
    required List<_i10.GameEvent>? events,
    required String? gameId,
    required String? winnerCompetitorId,
    required DateTime? endTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#appendEventsAndCompleteGame, [], {
              #events: events,
              #gameId: gameId,
              #winnerCompetitorId: winnerCompetitorId,
              #endTime: endTime,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i2.Game?> watchActiveGame() =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveGame, []),
            returnValue: _i4.Stream<_i2.Game?>.empty(),
          )
          as _i4.Stream<_i2.Game?>);

  @override
  _i4.Stream<List<_i2.Game>> watchCompletedGames({
    _i9.GameType? filterByType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchCompletedGames, [], {
              #filterByType: filterByType,
            }),
            returnValue: _i4.Stream<List<_i2.Game>>.empty(),
          )
          as _i4.Stream<List<_i2.Game>>);
}
