// Mocks generated by Mockito 5.4.6 from annotations
// in dart_lodge/test/features/game/domain/usecases/create_game_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dart_lodge/core/utils/constants.dart' as _i5;
import 'package:dart_lodge/features/game/domain/entities/competitor.dart'
    as _i6;
import 'package:dart_lodge/features/game/domain/entities/game.dart' as _i4;
import 'package:dart_lodge/features/game/domain/entities/game_event.dart'
    as _i9;
import 'package:dart_lodge/features/game/domain/models/game_state_snapshot.dart'
    as _i7;
import 'package:dart_lodge/features/game/domain/repositories/game_event_repository.dart'
    as _i8;
import 'package:dart_lodge/features/game/domain/repositories/game_repository.dart'
    as _i2;
import 'package:dart_lodge/features/players/domain/entities/player.dart'
    as _i11;
import 'package:dart_lodge/features/players/domain/repositories/player_repository.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GameRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRepository extends _i1.Mock implements _i2.GameRepository {
  MockGameRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Game?> getActiveGame() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveGame, []),
            returnValue: _i3.Future<_i4.Game?>.value(),
          )
          as _i3.Future<_i4.Game?>);

  @override
  _i3.Future<_i4.Game?> getGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getGame, [gameId]),
            returnValue: _i3.Future<_i4.Game?>.value(),
          )
          as _i3.Future<_i4.Game?>);

  @override
  _i3.Future<List<_i4.Game>> getCompletedGames({
    int? limit = 20,
    int? offset = 0,
    _i5.GameType? filterByType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedGames, [], {
              #limit: limit,
              #offset: offset,
              #filterByType: filterByType,
            }),
            returnValue: _i3.Future<List<_i4.Game>>.value(<_i4.Game>[]),
          )
          as _i3.Future<List<_i4.Game>>);

  @override
  _i3.Future<List<_i6.Competitor>> getCompetitors(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getCompetitors, [gameId]),
            returnValue: _i3.Future<List<_i6.Competitor>>.value(
              <_i6.Competitor>[],
            ),
          )
          as _i3.Future<List<_i6.Competitor>>);

  @override
  _i3.Future<void> createGame(
    _i4.Game? game,
    List<_i6.Competitor>? competitors,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createGame, [game, competitors]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveGameState(
    String? gameId,
    _i7.GameStateSnapshot? state,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveGameState, [gameId, state]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> completeGame({
    required String? gameId,
    required String? winnerCompetitorId,
    required DateTime? endTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeGame, [], {
              #gameId: gameId,
              #winnerCompetitorId: winnerCompetitorId,
              #endTime: endTime,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i4.Game?> watchActiveGame() =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveGame, []),
            returnValue: _i3.Stream<_i4.Game?>.empty(),
          )
          as _i3.Stream<_i4.Game?>);

  @override
  _i3.Stream<List<_i4.Game>> watchCompletedGames({
    _i5.GameType? filterByType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchCompletedGames, [], {
              #filterByType: filterByType,
            }),
            returnValue: _i3.Stream<List<_i4.Game>>.empty(),
          )
          as _i3.Stream<List<_i4.Game>>);
}

/// A class which mocks [GameEventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameEventRepository extends _i1.Mock
    implements _i8.GameEventRepository {
  MockGameEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i9.GameEvent>> getEventsForGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventsForGame, [gameId]),
            returnValue: _i3.Future<List<_i9.GameEvent>>.value(
              <_i9.GameEvent>[],
            ),
          )
          as _i3.Future<List<_i9.GameEvent>>);

  @override
  _i3.Future<List<_i9.GameEvent>> getEventsSince(
    String? gameId,
    int? afterSequence,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEventsSince, [gameId, afterSequence]),
            returnValue: _i3.Future<List<_i9.GameEvent>>.value(
              <_i9.GameEvent>[],
            ),
          )
          as _i3.Future<List<_i9.GameEvent>>);

  @override
  _i3.Future<List<_i9.GameEvent>> getUnsyncedEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedEvents, []),
            returnValue: _i3.Future<List<_i9.GameEvent>>.value(
              <_i9.GameEvent>[],
            ),
          )
          as _i3.Future<List<_i9.GameEvent>>);

  @override
  _i3.Future<int> getLatestSequence(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestSequence, [gameId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> appendEvent(_i9.GameEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#appendEvent, [event]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> appendEvents(List<_i9.GameEvent>? events) =>
      (super.noSuchMethod(
            Invocation.method(#appendEvents, [events]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markSynced(List<String>? eventIds) =>
      (super.noSuchMethod(
            Invocation.method(#markSynced, [eventIds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateGlobalSequences(Map<String, int>? eventIdToSequence) =>
      (super.noSuchMethod(
            Invocation.method(#updateGlobalSequences, [eventIdToSequence]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i9.GameEvent>> watchEventsForGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#watchEventsForGame, [gameId]),
            returnValue: _i3.Stream<List<_i9.GameEvent>>.empty(),
          )
          as _i3.Stream<List<_i9.GameEvent>>);
}

/// A class which mocks [PlayerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerRepository extends _i1.Mock implements _i10.PlayerRepository {
  MockPlayerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i11.Player>> getAllPlayers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPlayers, []),
            returnValue: _i3.Future<List<_i11.Player>>.value(<_i11.Player>[]),
          )
          as _i3.Future<List<_i11.Player>>);

  @override
  _i3.Future<_i11.Player?> getPlayer(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlayer, [playerId]),
            returnValue: _i3.Future<_i11.Player?>.value(),
          )
          as _i3.Future<_i11.Player?>);

  @override
  _i3.Future<void> createPlayer(_i11.Player? player) =>
      (super.noSuchMethod(
            Invocation.method(#createPlayer, [player]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updatePlayerName(String? playerId, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlayerName, [playerId, name]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> touchPlayer(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#touchPlayer, [playerId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePlayer(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlayer, [playerId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i11.Player>> watchAllPlayers() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllPlayers, []),
            returnValue: _i3.Stream<List<_i11.Player>>.empty(),
          )
          as _i3.Stream<List<_i11.Player>>);
}
