// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'player_stats.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_PlayerStats _$PlayerStatsFromJson(Map<String, dynamic> json) => _PlayerStats(
  playerId: json['playerId'] as String,
  gameType: $enumDecode(_$GameTypeEnumMap, json['gameType']),
  totalGames: (json['totalGames'] as num).toInt(),
  gamesWon: (json['gamesWon'] as num).toInt(),
  winRate: (json['winRate'] as num).toDouble(),
  threeDartAverage: (json['threeDartAverage'] as num).toDouble(),
  checkoutPercentage: (json['checkoutPercentage'] as num?)?.toDouble(),
  highestCheckout: (json['highestCheckout'] as num?)?.toInt(),
  highestTurnScore: (json['highestTurnScore'] as num).toInt(),
  totalDartsThrown: (json['totalDartsThrown'] as num).toInt(),
  dartsPerLeg: (json['dartsPerLeg'] as num).toDouble(),
  bustRate: (json['bustRate'] as num).toDouble(),
  legsPlayed: (json['legsPlayed'] as num?)?.toInt() ?? 0,
  legsWon: (json['legsWon'] as num?)?.toInt() ?? 0,
  firstNinePpr: (json['firstNinePpr'] as num?)?.toDouble(),
  sixtyPlusTurns: (json['sixtyPlusTurns'] as num?)?.toInt() ?? 0,
  oneHundredPlusTurns: (json['oneHundredPlusTurns'] as num?)?.toInt() ?? 0,
  oneFortyPlusTurns: (json['oneFortyPlusTurns'] as num?)?.toInt() ?? 0,
  oneEightyTurns: (json['oneEightyTurns'] as num?)?.toInt() ?? 0,
  bestLegPpr: (json['bestLegPpr'] as num?)?.toDouble(),
  bestFirstNinePpr: (json['bestFirstNinePpr'] as num?)?.toDouble(),
  avgCheckoutScore: (json['avgCheckoutScore'] as num?)?.toDouble(),
  bestGameCheckoutPercentage: (json['bestGameCheckoutPercentage'] as num?)
      ?.toDouble(),
  marksPerTurn: (json['marksPerTurn'] as num?)?.toDouble(),
  hitRate: (json['hitRate'] as num?)?.toDouble(),
  sixMarkTurns: (json['sixMarkTurns'] as num?)?.toInt() ?? 0,
  nineMarkTurns: (json['nineMarkTurns'] as num?)?.toInt() ?? 0,
  bestLegMpt: (json['bestLegMpt'] as num?)?.toDouble(),
  bestGameHitRate: (json['bestGameHitRate'] as num?)?.toDouble(),
  atcCompletions: (json['atcCompletions'] as num?)?.toInt() ?? 0,
  atcHitRate: (json['atcHitRate'] as num?)?.toDouble(),
  atcAvgTurns: (json['atcAvgTurns'] as num?)?.toDouble(),
  atcBestTurns: (json['atcBestTurns'] as num?)?.toInt(),
  atcSegmentHits:
      (json['atcSegmentHits'] as Map<String, dynamic>?)?.map(
        (k, e) => MapEntry(int.parse(k), (e as num).toInt()),
      ) ??
      const <int, int>{},
  atcSegmentAttempts:
      (json['atcSegmentAttempts'] as Map<String, dynamic>?)?.map(
        (k, e) => MapEntry(int.parse(k), (e as num).toInt()),
      ) ??
      const <int, int>{},
  bobs27AvgScore: (json['bobs27AvgScore'] as num?)?.toDouble(),
  bobs27BestScore: (json['bobs27BestScore'] as num?)?.toInt(),
  bobs27CompletionRate: (json['bobs27CompletionRate'] as num?)?.toDouble(),
  bobs27DoubleHitRate: (json['bobs27DoubleHitRate'] as num?)?.toDouble(),
  shanghaiAvgScore: (json['shanghaiAvgScore'] as num?)?.toDouble(),
  shanghaiBestScore: (json['shanghaiBestScore'] as num?)?.toInt(),
  shanghaiCount: (json['shanghaiCount'] as num?)?.toInt() ?? 0,
  catch40AvgScore: (json['catch40AvgScore'] as num?)?.toDouble(),
  catch40BestScore: (json['catch40BestScore'] as num?)?.toInt(),
  catch40TwoDartCheckouts:
      (json['catch40TwoDartCheckouts'] as num?)?.toInt() ?? 0,
  catch40ThreeDartCheckouts:
      (json['catch40ThreeDartCheckouts'] as num?)?.toInt() ?? 0,
  catch40FourSixDartCheckouts:
      (json['catch40FourSixDartCheckouts'] as num?)?.toInt() ?? 0,
  catch40FailedCheckouts:
      (json['catch40FailedCheckouts'] as num?)?.toInt() ?? 0,
  checkoutAttempts: (json['checkoutAttempts'] as num?)?.toInt() ?? 0,
  checkoutSuccesses: (json['checkoutSuccesses'] as num?)?.toInt() ?? 0,
  checkoutSuccessRate: (json['checkoutSuccessRate'] as num?)?.toDouble(),
);

Map<String, dynamic> _$PlayerStatsToJson(_PlayerStats instance) =>
    <String, dynamic>{
      'playerId': instance.playerId,
      'gameType': _$GameTypeEnumMap[instance.gameType]!,
      'totalGames': instance.totalGames,
      'gamesWon': instance.gamesWon,
      'winRate': instance.winRate,
      'threeDartAverage': instance.threeDartAverage,
      'checkoutPercentage': instance.checkoutPercentage,
      'highestCheckout': instance.highestCheckout,
      'highestTurnScore': instance.highestTurnScore,
      'totalDartsThrown': instance.totalDartsThrown,
      'dartsPerLeg': instance.dartsPerLeg,
      'bustRate': instance.bustRate,
      'legsPlayed': instance.legsPlayed,
      'legsWon': instance.legsWon,
      'firstNinePpr': instance.firstNinePpr,
      'sixtyPlusTurns': instance.sixtyPlusTurns,
      'oneHundredPlusTurns': instance.oneHundredPlusTurns,
      'oneFortyPlusTurns': instance.oneFortyPlusTurns,
      'oneEightyTurns': instance.oneEightyTurns,
      'bestLegPpr': instance.bestLegPpr,
      'bestFirstNinePpr': instance.bestFirstNinePpr,
      'avgCheckoutScore': instance.avgCheckoutScore,
      'bestGameCheckoutPercentage': instance.bestGameCheckoutPercentage,
      'marksPerTurn': instance.marksPerTurn,
      'hitRate': instance.hitRate,
      'sixMarkTurns': instance.sixMarkTurns,
      'nineMarkTurns': instance.nineMarkTurns,
      'bestLegMpt': instance.bestLegMpt,
      'bestGameHitRate': instance.bestGameHitRate,
      'atcCompletions': instance.atcCompletions,
      'atcHitRate': instance.atcHitRate,
      'atcAvgTurns': instance.atcAvgTurns,
      'atcBestTurns': instance.atcBestTurns,
      'atcSegmentHits': instance.atcSegmentHits.map(
        (k, e) => MapEntry(k.toString(), e),
      ),
      'atcSegmentAttempts': instance.atcSegmentAttempts.map(
        (k, e) => MapEntry(k.toString(), e),
      ),
      'bobs27AvgScore': instance.bobs27AvgScore,
      'bobs27BestScore': instance.bobs27BestScore,
      'bobs27CompletionRate': instance.bobs27CompletionRate,
      'bobs27DoubleHitRate': instance.bobs27DoubleHitRate,
      'shanghaiAvgScore': instance.shanghaiAvgScore,
      'shanghaiBestScore': instance.shanghaiBestScore,
      'shanghaiCount': instance.shanghaiCount,
      'catch40AvgScore': instance.catch40AvgScore,
      'catch40BestScore': instance.catch40BestScore,
      'catch40TwoDartCheckouts': instance.catch40TwoDartCheckouts,
      'catch40ThreeDartCheckouts': instance.catch40ThreeDartCheckouts,
      'catch40FourSixDartCheckouts': instance.catch40FourSixDartCheckouts,
      'catch40FailedCheckouts': instance.catch40FailedCheckouts,
      'checkoutAttempts': instance.checkoutAttempts,
      'checkoutSuccesses': instance.checkoutSuccesses,
      'checkoutSuccessRate': instance.checkoutSuccessRate,
    };

const _$GameTypeEnumMap = {
  GameType.x01: 'x01',
  GameType.cricket: 'cricket',
  GameType.aroundTheClock: 'aroundTheClock',
  GameType.killer: 'killer',
  GameType.baseball: 'baseball',
  GameType.golf: 'golf',
  GameType.shanghai: 'shanghai',
  GameType.scram: 'scram',
  GameType.halveIt: 'halveIt',
  GameType.highScore: 'highScore',
  GameType.blindCricket: 'blindCricket',
  GameType.blindGolf: 'blindGolf',
  GameType.blindKiller: 'blindKiller',
  GameType.blindShanghai: 'blindShanghai',
  GameType.chaseTheDragon: 'chaseTheDragon',
  GameType.catch40: 'catch40',
  GameType.bobs27: 'bobs27',
  GameType.checkoutPractice: 'checkoutPractice',
  GameType.countUp: 'countUp',
};
